[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 1
remappings = [
  "cozy-safety-module-libs/=lib/cozy-safety-module-libs/src",
]
fs_permissions = [{ access = "read", path = "./script/input"}]


[profile.default.fuzz]
runs = 1024

[profile.default.fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 2
wrap_comments = true